---
# tasks file for manage-by-helm

    - name: Install helm chart from a repo specifying path
      become: yes
      kubernetes.core.helm:
        chart_repo_url: "https://{{ item.key }}"
        chart_ref: "{{ item.value.ref }}"
        state: present
        name: "{{ item.value.name }}"
        namespace: "{{ item.value.namespace }}"
        create_namespace: true
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      loop: "{{ helm | dict2items  }}"
      loop_control:
        label: "{{ item.key }}"