---
# tasks file for install-flannel

    - name: install Pod network
      become: yes
#      become_user: cloudshell
      shell: kubectl --cache-dir='/home/cloudshell/.kube/cache' --kubeconfig='/home/cloudshell/.kube/config' apply -f ./roles/install-flannel/files/kube-flannel.yml 
#      args:
#        chdir: /home/cloudshell