- hosts: jenkins
  vars:
   hostname: k8s
   username: jenkins
  become: yes
  tasks:
    - name: create user
      user: 
        name: "{{username}}"
        append: yes
        groups: users
        state: present
        createhome: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
#        ssh_key_file: .ssh/id_rsa

    - name: allow to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: '{{username}} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: user"s home
      command: echo ~{{username}}
      register: userhome

    - name: set up authorized keys for the  user
      become: yes
#      become_user: root
      authorized_key:
        user: "{{username}}" 
        key: "{{ lookup('file', '{{userhome.stdout_lines[0]}}/.ssh/id_rsa.pub') }}"
#      args:
#        path: "{{userhome.stdout_lines[0]}}" 
#        keyfile: .ssh/id_rsa.pub
#      with_file:
#        - .ssh/id_rsa.pub

    - name: Inject SSH public key into remote system
#      become: yes
#      become_user: "{{username}}"
      command: ssh_copy_id -i "{{ item }}" "{{ username }}"@"{{ hostname }}" 
      with_file:
        - "{{userhome.stdout_lines[0]}}/.ssh/id_rsa.pub" 
