- hosts: k8s
  become: yes
  roles:
    - role: nn-off
    - role: containerd
  #become_user: cloudshell
  tasks:
    - debug:
        var: "{{ item.key }}{{ item.value }}{{ item.path}}"
#      with_dict: 
      with_subelements:
        - "{{ content.tarball }}"
#        - path
#        - "{{ content.install}}"
#        - "{{ content.service}}"
#      when: " item.value | regex_search('*gz') "
 