- hosts: k8s
  become: yes
  roles:
#    - role: nn-off
    - role: containerd
  #become_user: cloudshell
  tasks:
    - debug:
        var: "{{ item.1 }}"#{{ item.value }}"#{{ item.path}}"
#      with_dict: 
#      with_list:
      with_subelements:
        - "{{ content.tarball }}"
        - path
#        - "{{ content.install}}"
#        - "{{ content.service}}"
#      when: " item.value | regex_search('*gz') "
 