- hosts: k8s
  vars:  
   content:
     dn-tarball:
     - uri: github.com/containerd/containerd/releases/download/v1.6.4/ 
       with: 
         - name: containerd-1.6.4-linux-amd64.tar.gz
           path: /usr/local
     - uri: github.com/containernetworking/plugins/releases/download/v1.1.1/ 
       with: 
         - name: cni-plugins-linux-amd64-v1.1.1.tgz
           path: /opt/cni/bin
     dn-install:
     - uri: github.com/opencontainers/runc/releases/download/v1.1.4/
       with:
         - name: runc.amd64
           path: /usr/local/sbin/runc
     service:
     - uri: raw.githubusercontent.com/containerd/containerd/main/
       with:
         - name: containerd.service
           path: /usr/local/lib/systemd/system/containerd.service
  become: yes
  roles:
#    - role: nn-off
#    - role: containerd
  #become_user: cloudshell
  tasks:
#    - debug:
#        var: item.0
#      with_list:
#        - "{{ content.tarball }}"
        
    - debug:
        msg: 
          - "{{ item.0.uri }} '---'"
          #- "{{item[0.0]}} '00 " #{{ item.value }}"#{{ item.path}}"
#          - "{{item[1]}}"
          - "{{ item.1.name }} ----"
          - "{{ item.1.path }} -----"
#      with_dict: 
#      with_list:
      with_subelements:
#        - "{{ content.dn-* }}"
        - "{{ content.dn-tarball }}"
#        - "{{ content.dn-install }}"
        - with
#        - "{{ content.install}}"
#        - "{{ content.service}}"
#      when: " item.value | regex_search('*gz') "
 