- hosts: k8s
  become: yes
  roles:
#    - role: nn-off
    - role: containerd
  #become_user: cloudshell
  tasks:
    - debug:
        var: item.0
      with_list:
        - "{{ content.tarball }}"
        
    - debug:
        msg: 
          - "{{item[0]}} '---'"
          - "{{item[0.0]}} '00 " #{{ item.value }}"#{{ item.path}}"
          - "{{item[1]}}"
#      with_dict: 
#      with_list:
      with_subelements:
        - "{{ content.tarball }}"
        - path
#        - "{{ content.install}}"
#        - "{{ content.service}}"
#      when: " item.value | regex_search('*gz') "
 