---
# vars file for k8s-prereq

content_files:
  k8s.conf: /etc/modules-load.d
  k8sys.conf: /etc/sysctl.d
  
content_modules:
  - overlay
  - br_netfilter

k8s_app:
  - kubeadm
  - kubelet
  - kubectl