---
# tasks file for k8s-copy-admin

 - block:
 
    - name: create .kube directory
      file:
        path: /home/cloudshell/.kube
        state: directory
        owner: cloudshell
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/cloudshell/.kube/config
        remote_src: yes
        owner: cloudshell
        mode: 0700
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
        
   become: yes
