---
# tasks file for k8s-prereq

 - block:
 
   - name: copy systemd conf files
     copy:
       src: "{{ item.key }}"
       dest: "{{ item.value }}"
       owner: root
       group: root
       mode: u=rw,g=r,o=r
     with_dict: "{{ content_files }}"
     
   - name: load kernel modules 
     modprobe:
       name: "{{ item }}"
       state: present
     with_items: "{{ content_modules }}"

   - name: sysctl --system
     shell: sysctl --system
     
   when: true
   become: yes