---
# tasks file for k8s-prereq

 - block:
 
   - name: install app dependencies
     package:
       name: "{{ dep_app }}"
       state: present
      
   - name: load kernel modules 
     modprobe:
       name: "{{ item }}"
       state: present
     with_items: "{{ content_modules }}"

   - name: sysctl --system
     shell: sysctl --system
     
   when: true
   become: yes