---
# vars file for containerd

content:
  tarball:
    github.com/containerd/containerd/releases/download/v1.6.4/ : 
      containerd-1.6.4-linux-amd64.tar.gz
      path: /usr/local 
    github.com/containernetworking/plugins/releases/download/v1.1.1/ : cni-plugins-linux-amd64-v1.1.1.tgz
      path: /opt/cni/bin
  install:
    github.com/opencontainers/runc/releases/download/v1.1.4/ : runc.amd64
  service: 
    raw.githubusercontent.com/containerd/containerd/main/ : containerd.service
      path: /usr/local/lib/systemd/system/containerd.service