---
# tasks file for k8s
    - name: Unpack release key
      ansible.builtin.command:
        cmd: gpg --dearmor -o "{{ item.value.path }}kubernetes-apt-keyring.gpg" /tmp/"{{ item.value.name }}"
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      loop: "{{ content | dict2items |
                rejectattr('value.tag', 'search', 'file' ) |
                rejectattr('value.tag', 'search', 'j2t' ) |
                list }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Update repositories cache and install k8s packages
      ansible.builtin.apt:
        update_cache: yes
        name: "{{ k8s_app }}"
        state: present
      
    - name: Change various sysctl-settings
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
        reload: yes
        ignoreerrors: yes
      with_dict: "{{ sysctl_config }}"
