---
# tasks file for nn-off
- become: yes

 - debug:
     var: "{{ item }}"
   with_list: "{{ un.disb }}"


 - name: disable units
   systemd:
     name: "{{ item }}"
     state: stopped
     enabled: no
     masked: yes
   with_list: "{{ un.disb }}"