---
# tasks file for containerd

- name: Wget artifacts
  get_url:
    url: "https://{{ item.key }}{{ item.value }}"
    dest: "/tmp/{{ item.value }}"
    force: false
  with_dict: "{{ content }}"
 
- name: Extract archived
  unarchive:
    src:
