---
# tasks file for containerd

{#
- name: containerd block
  block:
   when: 1 == 0
#) 
  - name: Wget artifacts
    get_url:
      url: "https://{{ item.key }}{{ item.value.name }}"
      dest: "/tmp/{{ item.value.name }}"
      force: false
    loop: "{{ content | dict2items  }}"
    loop_control:
      label: "{{ item.key }}"
        
  - name: Copy artifacts
    copy:
      src:  "/tmp/{{ item.value.name }}"
      dest: "/tmp/{{ item.value.path }}"
      remote_src: yes
    loop: "{{ content | dict2items | selectattr('value.tag', 'search', 'service' ) | list }}"
    loop_control:
      label: "{{ item.key }}"
        
  - name: Extract archived
    unarchive:
      src:  "/tmp/{{ item.value.name }}"
      dest: "/tmp/{{ item.value.path }}"
      owner: root
      mode:  0755
      remote_src: yes
    loop: "{{ content | dict2items | selectattr('value.tag', 'search', 'tar' ) | list }}"
    loop_control:
      label: "{{ item.key }}"

  - name: Install module
    shell: install -m 755 "/tmp/{{ item.value.name }}" "/tmp/{{ item.value.path }}"
      become: yes
    loop: "{{ content | dict2items | selectattr('value.tag', 'search', 'install' ) | list }}"
    loop_control:
      label: "{{ item.key }}"