---
# tasks file for containerd
    become: yes

  - name: Wget artifacts
    get_url:
      url: "https://{{ item.key }}{{ item.value.name }}"
      dest: "/tmp/{{ item.value.name }}"
      force: false
    loop: "{{ content | dict2items  }}"
    loop_control:
      label: "{{ item.key }}"

  - name: Creates directory
    file:
      path: "/tmp{{ item.value.path }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    loop: "{{ content | dict2items  }}"
    loop_control:
      label: "{{ item.key }}"

  - name: Copy artifacts
    become: yes
    copy:
      src:  "/tmp/{{ item.value.name }}"
      dest: "/tmp{{ item.value.path }}"
      remote_src: yes
    notify:
      - reload systemd
    loop: "{{ content | dict2items | selectattr('value.tag', 'search', 'service' ) | list }}"
    loop_control:
      label: "{{ item.key }}"
        
  - name: Extract archived
    become: yes
    unarchive:
      src:  "/tmp/{{ item.value.name }}"
      dest: "/tmp{{ item.value.path }}"
      owner: root
      mode:  0755
      remote_src: yes
    loop: "{{ content | dict2items | selectattr('value.tag', 'search', 'tar' ) | list }}"
    loop_control:
      label: "{{ item.key }}"

  - name: Install module
    become: yes
    shell: install -m 755 "/tmp/{{ item.value.name }}" "/tmp{{ item.value.path }}"
    args:
      creates: "/tmp{{ item.value.path }}/{{ item.value.name }}"
    loop: "{{ content | dict2items | selectattr('value.tag', 'search', 'install' ) | list }}"
    loop_control:
      label: "{{ item.key }}"
      
 ### 
 
  - name: containerd file config.toml
    copy:
      src: config.toml
      dest: /etc/containerd
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    notify:
      - restart systemd
    
  - name: cni template file
    template:
      src: 10-containerd-net.conflist.j2
      dest: /etc/cni/net.d
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: cni lo file
    copy:
      src: 99-loopback.conf
      dest: /etc/cni/net.d
      owner: root
      group: root
      mode: u=rw,g=r,o=r

